from typing import Any, Callable, Iterator, List, Optional, Tuple, Union
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.image import AxesImage
from matplotlib.collections import PathCollection

class symple_plot:
    ax: Axes
    def __init__(self, ax: Axes) -> None: ...
    
    # 🌟 究極のハック：配列のようにアクセスされたら、symple_plotを返すようにする！
    def __getitem__(self, key: Any) -> 'symple_plot': ...
    def __iter__(self) -> Iterator['symple_plot']: ...
    def flatten(self) -> List['symple_plot']: ...
    
    # 以下、既存のメソッド
    def plot(self, X: Any, Y: Any, **kwargs: Any) -> Axes: ...
    def scatter(self, X: Any, Y: Any, **kwargs: Any) -> Axes: ...
    def pre_set(self, X: Any, Y: Any, **kwargs: Any) -> Axes: ...
    def tdscatter(self, X: Any, Y: Any, Z: Any, **kwargs: Any) -> Tuple[Axes, List[PathCollection]]: ...
    def tdplot(self, X: Any, Y: Any, Z: Any, **kwargs: Any) -> Tuple[Axes, List[Any]]: ...
    def imshow(self, X: Any, Y: Any, Z: Any, vmax: float, **kwargs: Any) -> Tuple[Axes, AxesImage]: ...
    def add_panel_label(self, text: str, x: float = ..., y: float = ..., fontsize: Optional[int] = ..., weight: str = ...) -> Axes: ...
    def twiny(self, **kwargs: Any) -> 'symple_plot': ...
    def twinx(self, **kwargs: Any) -> 'symple_plot': ...
    def secondary_yaxis(self, functions: Union[Callable, Tuple[Callable, Callable]], location: str = ..., **kwargs: Any) -> Axes: ...
    def secondary_xaxis(self, functions: Union[Callable, Tuple[Callable, Callable]], location: str = ..., **kwargs: Any) -> Axes: ...
    def Regression(self, regr: Union[int, Callable], directory: str = ..., **kwargs: Any) -> Axes: ...
    def add_inset_zoom(self, xlim: Optional[List[float]] = ..., ylim: Optional[List[float]] = ..., bounds: Union[str, List[float]] = ..., margin: float = ..., draw_lines: bool = ..., **kwargs: Any) -> Optional[Axes]: ...

# 🌟 戻り値は常に symple_plot だと教えておく
def create_symple_plots(
    nrows: int = 1, ncols: int = 1, figsize: Optional[Tuple[float, float]] = None,
    style: Optional[str] = None, auto_label: bool = False, flush: bool = False, **kwargs: Any
) -> Tuple[plt.Figure, symple_plot]: ...

def set_style(mode: str = ...) -> None: ...